'''
Pentagon numbers
Problem 44 
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| 
is minimised; what is the value of D?
'''
from math import sqrt


def is_pentagonal(num):
    d = sqrt((1+24*num))
    x = (1 + d) / 6
    if int(x) == x:
        return True

searching = True
i = 1

while searching:
    i += 1
    n = (3 * (i ** 2) - i) / 2

    for j in range(i-1, 0, -1):
        m = (3 * (j ** 2) - j) / 2
        if is_pentagonal(abs(n-m)) and is_pentagonal((n+m)):
            print("Pj:", i, "Pk:", j)
            print("D:", int(abs(n-m)))
            x = False
            break
